name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        os: [windows-latest]
      
        
    steps:      
      - name: Checkout code
        uses: actions/checkout@v2








        

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Start MySQL container
        run: |
          docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=root -d mysql:8.0.36
        shell: bash

      - name: Check MySQL version
        run: |
          echo "MySQL Version:"
          mysql --version
        shell: bash








      - name: Set executable permission
        run: chmod +x node_modules/.bin/jest
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Run Jest with --runInBand --detectOpenHandles --forceExit
        run: npm test

# Additional features (potentially added)
# Linting
# Code coverage tools to ensure that a certain percentage of code is covered by tests
# Integration tests to validate interactions between different parts of the system
# Building and deploying the application? xxx
