name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set executable permission
        run: chmod +x node_modules/.bin/jest

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

    #  - name: Navigate to Backend directory and Run node app.js
    #    run: cd Backend && node app.js

      - name: Run Jest with --runInBand --detectOpenHandles --forceExit
        run: npm test

      #- name: Run unit tests 
      #  run: npm test 

# Additional features (potentially added)
# Linting
# Code coverage tools to ensure that a certain percentage of code is covered by tests
# Integration tests to validate interactions between different parts of the system
# Building and deploying the application?
