name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.36  # Updated MySQL version (e.g., 8.0)
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3



      


    steps:
      - name: Pull MySQL Docker image
        run: docker pull mysql:8.0.36
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set executable permission
        run: chmod +x node_modules/.bin/jest
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Run Jest with --runInBand --detectOpenHandles --forceExit
        run: npm test

# Additional features (potentially added)
# Linting
# Code coverage tools to ensure that a certain percentage of code is covered by tests
# Integration tests to validate interactions between different parts of the system
# Building and deploying the application?
